name: Update gist with WakaTime stats.
on:
  schedule:
    - cron: "0 0 * * *"
    
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: fb86d12bc2904afe0fb553eb68bac7dd
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
